Feature scss
RTO-Websites/WordPress-Plugin-Boilerplate pull request #2
Opened 2019-07-22 12:56 UTC by crazypsycho

Just add scss for Admin&Public with gulp

2019-07-22 14:36 UTC, eac0n requested changes
`node_modules` should be added to `.gitignore`

2019-07-22 14:36 UTC, eac0n commented on plugin-name/Public/scss/partials/_main.scss
> +body.public {
Was this added on purpose?

2019-07-22 14:44 UTC, crazypsycho commented on plugin-name/Public/scss/partials/_main.scss
> +body.public {
Is removed

2019-07-24 06:55 UTC, eac0n approved these changes

2019-07-24 06:56 UTC, merged